set wrap
set pastetoggle=<F5>
set number
set relativenumber
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set ignorecase
set smartcase
set incsearch
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
let &colorcolumn=join(range(76,999),",")
autocmd bufreadpre * setlocal textwidth=75
highlight ColorColumn ctermbg=233 guibg=#2c2d27
hi CursorLine   cterm=NONE ctermbg=237
set cursorline!
set encoding=utf-8
let g:netrw_home=$VIMHOME
set viminfo+=n$VIMHOME/viminfo
set runtimepath+=$VIMHOME/vim
set directory=$VIMHOME/swap//
set backupdir=$VIMHOME/backup//
set undodir=$VIMHOME/undo//
set undofile
set nocompatible
set mouse=""
set noerrorbells
:map Q <Nop>
filetype plugin indent on
syntax on
au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
autocmd BufWritePre * %s/\s\+$//e
